export const ACTION = {
    ALL_CASES: "ALL_CASES",
    ALL_OFFICERS: "ALL_OFFICERS",

    SAVE_APPROVED_OFFICERS: "SAVE_APPROVED_OFFICERS",

    ONE_CASE: "ONE_CASE",
    ONE_OFFICER: "ONE_OFFICER",
    
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",

    NEW_CASE: "NEW_CASE",

    LOAD_DONE: "LOAD_DONE",

    MSG: "MSG"
}